import { useState } from "react";
import { Activity, Ambulance, ArrowRight, BellRing, Building2, CheckCircle2, ClipboardList, Droplets, HeartPulse, LogOut, MapPinned, PackageCheck, Radio, Shield, Siren, Users } from "lucide-react";
import Dashboard from "./Dashboard";
import { updateResource } from "../services/auth";

const ROLE_META = {
  hospital:{label:"Hospital / Medical",icon:HeartPulse,accent:"text-rose-300",bg:"bg-rose-400/10",title:"Medical Operations",subtitle:"Capacity, patient flow and emergency medical resources."},
  police:{label:"Police / Law Enforcement",icon:Shield,accent:"text-blue-300",bg:"bg-blue-400/10",title:"Public Safety Operations",subtitle:"Routes, evacuation corridors and incident security."},
  transport:{label:"Emergency Transport",icon:Ambulance,accent:"text-amber-300",bg:"bg-amber-400/10",title:"Transport Operations",subtitle:"Vehicles, dispatch capacity and emergency routes."},
  ngo:{label:"NGO / Relief Organization",icon:Users,accent:"text-emerald-300",bg:"bg-emerald-400/10",title:"Relief Operations",subtitle:"Shelters, volunteers, supplies and field requests."},
  citizen:{label:"Citizen / Public",icon:BellRing,accent:"text-cyan-300",bg:"bg-cyan-400/10",title:"Public Safety",subtitle:"Verified emergency information for people in affected areas."}
};
const DATA = {
  hospital:[["Available beds","18","12 critical-care beds",HeartPulse],["Ambulances","2","1 currently assigned",Ambulance],["Medical supplies","74%","Essential stock",PackageCheck],["Incoming alerts","03","2 require review",BellRing]],
  police:[["Active incidents","04","2 require priority",Siren],["Open routes","08","2 restricted",MapPinned],["Evacuation zones","03","Zone A is critical",Users],["Units available","17","4 deployed",Shield]],
  transport:[["Emergency vehicles","11","3 deployed",Ambulance],["Open routes","08","2 restricted",MapPinned],["Dispatch queue","05","2 high priority",ClipboardList],["Fuel readiness","86%","Operational",Activity]],
  ngo:[["Volunteers","64","18 deployed",Users],["Shelters","06","2 near capacity",Building2],["Food / water","78%","12 field requests",Droplets],["Open requests","09","4 high priority",ClipboardList]],
  citizen:[["Active emergencies","04","Verified incidents",Siren],["Safe shelters","06","2 near capacity",Building2],["Hospitals nearby","08","Live availability",HeartPulse],["Verified updates","12","Last update 2 min ago",BellRing]]
};

export default function RoleWorkspace({session,user,onLogout}) {
  const [openCoordinator,setOpenCoordinator]=useState(false);
  const [showUpdate,setShowUpdate]=useState(false);
  const FIELD_OPTIONS = {
    hospital: [["ambulances","Ambulances available","e.g. 0, 1, 2"],["beds","Available beds","e.g. 18"],["medical supplies","Medical supplies","e.g. 65%"],["patient surge","Patient surge","e.g. 12 critical patients"]],
    police: [["units available","Units available","e.g. 12"],["blocked route","Blocked route","e.g. Route B"],["evacuation status","Evacuation status","e.g. Zone A in progress"],["open routes","Open routes","e.g. 3"]],
    transport: [["emergency vehicles","Emergency vehicles","e.g. 5"],["route availability","Route availability","e.g. Route B open"],["dispatch capacity","Dispatch capacity","e.g. 2 vehicles"],["fuel readiness","Fuel readiness","e.g. 82%"]],
    ngo: [["shelters","Shelters available","e.g. 4"],["food / water stock","Food / water stock","e.g. 70%"],["volunteers","Volunteers available","e.g. 24"],["open requests","Open relief requests","e.g. 6"]],
    citizen: [["incident report","Incident report","e.g. Route B flooded"],["shelter status","Shelter status","e.g. shelter near capacity"],["local observation","Local observation","Describe what you see"]],
  };
  const [metric,setMetric]=useState("");
  const [value,setValue]=useState("");
  const [note,setNote]=useState("");
  const [updateState,setUpdateState]=useState("idle");
  const meta=ROLE_META[user.role];
  if(user.role==="government") return <div className="relative"><GovernmentShell user={user} onLogout={onLogout}/><Dashboard user={user} accessToken={session.access_token}/></div>;
  const Icon=meta.icon, cards=DATA[user.role];

  const submitUpdate=async(e)=>{
    e.preventDefault(); setUpdateState("loading");
    try{await updateResource(session.access_token,{metric,value,note});setUpdateState("success");setMetric("");setValue("");setNote("");}
    catch(err){setUpdateState(err.message||"Update failed.");}
  };

  return <div className="min-h-screen bg-[#0f1219] text-slate-100">
    <header className="sticky top-0 z-30 border-b border-white/8 bg-[#151923]/95 backdrop-blur-xl"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4 lg:px-8"><div className="flex items-center gap-3"><div className={`grid h-10 w-10 place-items-center rounded-xl ${meta.bg} ${meta.accent}`}><Icon size={19}/></div><div><p className="text-sm font-semibold">Emergency AI Coordinator</p><p className="text-[10px] uppercase tracking-[.16em] text-slate-600">{meta.label}</p></div></div><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><p className="text-xs font-semibold">{user.name}</p><p className="text-[10px] text-slate-500">{user.organization||meta.label}</p></div><button onClick={onLogout} className="grid h-9 w-9 place-items-center rounded-xl border border-white/8 text-slate-500 hover:border-white/15 hover:text-white"><LogOut size={16}/></button></div></div></header>
    <main className="mx-auto max-w-[1500px] px-5 py-8 lg:px-8">
      <div className="mb-8 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.2em] text-emerald-300"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-400"/>Live response network</div><h1 className="text-3xl font-semibold tracking-[-.03em]">{meta.title}</h1><p className="mt-2 text-sm text-slate-500">{meta.subtitle}</p></div><button onClick={()=>setOpenCoordinator(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-500 px-4 py-2.5 text-xs font-semibold shadow-lg shadow-indigo-950/30 hover:bg-indigo-400">Open Coordination Center <ArrowRight size={15}/></button></div>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,note,CardIcon])=><div key={label} className="rounded-2xl border border-white/8 bg-[#191e29] p-5"><div className="flex items-start justify-between"><div className="grid h-9 w-9 place-items-center rounded-xl bg-white/[.04] text-slate-400"><CardIcon size={17}/></div><span className="text-[9px] font-semibold uppercase tracking-wider text-emerald-300">Live</span></div><p className="mt-5 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs font-medium text-slate-300">{label}</p><p className="mt-1 text-[10px] text-slate-600">{note}</p></div>)}</div>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border border-white/8 bg-[#191e29] p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-slate-600">Current incident</p><h2 className="mt-1 text-lg font-semibold">FLOOD-001 · Zone A</h2></div><span className="rounded-full border border-red-400/20 bg-red-400/5 px-3 py-1 text-[10px] font-semibold uppercase tracking-wider text-red-300">Severity 9 · Critical</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["8,000","affected population"],["2","ambulances available"],["1","route blocked"]].map(([v,l])=><div key={l} className="rounded-xl border border-white/6 bg-white/[.02] p-4"><p className="text-xl font-semibold">{v}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-slate-600">{l}</p></div>)}</div><div className="mt-5 rounded-xl border border-indigo-400/15 bg-indigo-400/5 p-4"><div className="flex items-center gap-2 text-xs font-semibold text-indigo-200"><Radio size={14}/>Coordinator update</div><p className="mt-2 text-sm leading-6 text-slate-400">Route A is blocked. Emergency response should use active corridors while medical, evacuation and relief needs are coordinated across agencies.</p></div></section>
        <section className="rounded-2xl border border-white/8 bg-[#191e29] p-5"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-slate-600">Operations</p><div className="mt-4 space-y-2"><button onClick={()=>setShowUpdate(true)} className="flex w-full items-center justify-between rounded-xl border border-indigo-400/20 bg-indigo-400/5 px-4 py-3 text-left text-xs font-semibold text-indigo-200 hover:bg-indigo-400/10">Update resource availability <ArrowRight size={14}/></button>{["Acknowledge coordinator request","Share field status"].map(item=><button key={item} className="flex w-full items-center justify-between rounded-xl border border-white/7 bg-white/[.02] px-4 py-3 text-left text-xs font-medium text-slate-300 hover:border-indigo-400/20">{item}<ArrowRight size={14} className="text-slate-600"/></button>)}</div><div className="mt-5 flex items-center gap-2 text-[10px] text-emerald-300"><CheckCircle2 size={13}/>Updates are shared with authorized coordinators.</div></section></div>
    </main>
    {showUpdate&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-5 backdrop-blur-sm"><form onSubmit={submitUpdate} className="w-full max-w-md rounded-3xl border border-white/10 bg-[#191e29] p-6 shadow-2xl"><div className="mb-5"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-indigo-300">Operational update</p><h2 className="mt-2 text-xl font-semibold">Share current field status</h2><p className="mt-1 text-xs leading-5 text-slate-500">This update is written to the authenticated organization profile.</p></div><div className="space-y-4"><select required value={metric} onChange={e=>setMetric(e.target.value)} className="input"><option value="">Select operational metric</option>{(FIELD_OPTIONS[user.role]||[]).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><input required value={value} onChange={e=>setValue(e.target.value)} placeholder={(FIELD_OPTIONS[user.role]||[]).find(([key])=>key===metric)?.[2] || "Enter current status"} className="input"/><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Additional note" className="input min-h-24 resize-none"/></div>{updateState!=="idle"&&updateState!=="loading"&&<p className={`mt-4 text-xs ${updateState==="success"?"text-emerald-300":"text-red-300"}`}>{updateState==="success"?"✓ Operational update shared successfully.":updateState}</p>}<div className="mt-5 flex gap-2"><button type="button" onClick={()=>{setShowUpdate(false);setUpdateState("idle")}} className="flex-1 rounded-xl border border-white/10 px-4 py-3 text-xs font-semibold text-slate-400">Cancel</button><button disabled={updateState==="loading"} className="flex-1 rounded-xl bg-indigo-500 px-4 py-3 text-xs font-semibold">{updateState==="loading"?"Sharing…":"Share update"}</button></div></form><style>{`.input{width:100%;border-radius:12px;border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.025);padding:.75rem .85rem;font-size:.8rem;color:#fff;outline:none}.input::placeholder{color:#475569}.input:focus{border-color:rgba(129,140,248,.5)}`}</style></div>}
    {openCoordinator&&<div className="fixed inset-0 z-50 overflow-auto bg-[#0f1219]"><div className="sticky top-0 z-50 flex justify-end border-b border-white/8 bg-[#151923]/95 px-5 py-3 backdrop-blur-xl"><button onClick={()=>setOpenCoordinator(false)} className="rounded-xl border border-white/10 px-4 py-2 text-xs font-semibold text-slate-300">Back to role workspace</button></div><Dashboard user={user} accessToken={session.access_token}/></div>}
  </div>;
}
function GovernmentShell({user,onLogout}){return <div className="absolute right-5 top-4 z-40 flex items-center gap-3 lg:right-8"><div className="hidden text-right sm:block"><p className="text-xs font-semibold">{user.name}</p><p className="text-[10px] text-slate-500">{user.organization||"Government / Disaster Management"}</p></div><button onClick={onLogout} className="grid h-9 w-9 place-items-center rounded-xl border border-white/10 bg-black/20 text-slate-500 hover:text-white"><LogOut size={16}/></button></div>}
